export default {
  //   PAUSE_GAME_START: "PAUSE_GAME_START",
  //   PAUSE_GAME_FAILURE: "PAUSE_GAME_FAILURE",
  PAUSE_GAME_SUCCESS: "PAUSE_GAME_SUCCESS",

  //   UNPAUSE_GAME_START: "UNPAUSE_GAME_START",
  //   UNPAUSE_GAME_FAILURE: "UNPAUSE_GAME_FAILURE",
  UNPAUSE_GAME_SUCCESS: "UNPAUSE_GAME_SUCCESS",

  //   BEGIN_SIMULATING_START: "BEGIN_SIMULATING_START",
  BEGIN_SIMULATING_SUCCESS: "BEGIN_SIMULATING_SUCCESS",
  //   BEGIN_SIMULATING_FAILURE: "BEGIN_SIMULATING_FAILURE",

  //   STOP_SIMULATING_START: "STOP_SIMULATING_START",
  STOP_SIMULATING_SUCCESS: "STOP_SIMULATING_SUCCESS",
  //   STOP_SIMULATING_FAILURE: "STOP_SIMULATING_FAILURE",
};
